#chapter01
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hikari?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlpassword

#chapter??
spring.datasource.hikari:
  register-mbeans: true
  pool-name: hikari

spring.jmx.enabled: true

logging:
  level:
    root: info
    com.zaxxer.hikari.pool: debug
