server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlpassword
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=UTF-8&serverTimezone=UTC